import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
// Import the functions you need from the SDKs you need
import { initializeApp } from "firebase/app";
import { getAnalytics } from "firebase/analytics";
// TODO: Add SDKs for Firebase products that you want to use
// https://firebase.google.com/docs/web/setup#available-libraries

// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
const firebaseConfig = {
  apiKey: "AIzaSyCrQBshJaQYXwfssiSLXSmI8q-Eqa2XiCI",
  authDomain: "assignment-2-a57c9.firebaseapp.com",
  projectId: "assignment-2-a57c9",
  storageBucket: "assignment-2-a57c9.appspot.com",
  messagingSenderId: "611374587361",
  appId: "1:611374587361:web:d9027f28ddc8c8576586a0",
  measurementId: "G-VHNL4W58DF"
};

const app = initializeApp(firebaseConfig);
// const analytics = getAnalytics(app);

export const metadata = {
  title: 'Zepto Assignment',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
